"""
MarketPilot Models - Autonomous Agent domain models.
"""

from __future__ import annotations

from enum import Enum
from pydantic import BaseModel, Field
from typing import Tuple

class AgentDisposition(str, Enum):
    """The disposition of an agent proposal. Separate from trading SignalDirection."""
    LONG = "LONG"
    SHORT = "SHORT"
    ABSTAIN = "ABSTAIN"
    RESEARCH_ONLY = "RESEARCH_ONLY"

class MarketThesis(BaseModel):
    """AI-generated market thesis and interpretation."""
    model_config = {"frozen": True}
    regime_interpretation: str
    opportunity_assessment: str
    agent_confidence_rationale: str

class AgentModelProvenance(BaseModel):
    """Provenance tracking for the LLM model that generated the proposal."""
    model_config = {"frozen": True}
    provider: str
    model_version: str
    prompt_policy_version: str
    toolset_version: str

class StrategyActivationProposal(BaseModel):
    """Structured proposal generated by the AI agent to activate a strategy."""
    model_config = {"frozen": True}
    proposal_id: str
    agent_run_id: str
    created_at: float
    market_snapshot_id: str
    schema_version: str
    strategy_registry_version: str
    
    proposed_disposition: AgentDisposition
    target_strategy_families: Tuple[str, ...]
    thesis: MarketThesis
    provider_provenance: AgentModelProvenance

class AgentInvocationDecision(BaseModel):
    """Record of the deterministic AgentInvocationPolicy's decision to invoke the LLM or not."""
    model_config = {"frozen": True}
    invocation_id: str
    input_snapshot_ids: Tuple[str, ...]
    invoked: bool
    outcome_reason: str
    policy_version: str
    model_target: str
    token_budget_context: Tuple[Tuple[str, str], ...]
