"""
MarketPilot Models - Execution domain models.
"""

from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, Field

from marketpilot.models.strategy import SignalDirection


class SubmissionState(StrEnum):
    """The lifecycle state of a submission attempt."""

    PREPARED = "PREPARED"
    AUTHORIZED = "AUTHORIZED"
    NETWORK_ATTEMPT_STARTED = "NETWORK_ATTEMPT_STARTED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    UNKNOWN = "UNKNOWN"
    ABSENCE_CONFIRMED = "ABSENCE_CONFIRMED"
    TERMINAL_REJECTED = "TERMINAL_REJECTED"
    CANCELED = "CANCELED"


class FillState(StrEnum):
    """The fill state of a logical order."""

    UNFILLED = "UNFILLED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"


class ProtectionState(StrEnum):
    """The safety state of the execution's protective stop."""

    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    MISMATCH = "MISMATCH"
    UNSAFE = "UNSAFE"


class PermitAction(StrEnum):
    """The type of network mutation authorized by a permit."""

    CREATE = "CREATE"
    CANCEL = "CANCEL"
    REDUCE_ONLY_CLOSE = "REDUCE_ONLY_CLOSE"


class ExecutionIntent(BaseModel, frozen=True):
    """
    Immutable intent derived directly from a committed PortfolioAllocationToken.
    It represents the original admitted truth and bounds.
    """

    intent_id: str
    allocation_token_id: str
    logical_order_id: str
    symbol: str
    side: SignalDirection
    original_qty: Decimal
    executable_entry: Decimal
    effective_stop: Decimal
    take_profit: Decimal | None = None
    environment: str


class EmergencyCloseIntent(BaseModel, frozen=True):
    """
    Immutable intent to flatten a position that lacks protection.
    Sized from a fresh actual-position snapshot, NOT the original intent.
    """

    intent_id: str
    logical_order_id: str
    symbol: str
    side: SignalDirection
    quantity: Decimal
    reduce_only: Literal[True] = True
    position_idx: Literal[0] = 0
    purpose: Literal["RISK_REDUCTION_ONLY"] = "RISK_REDUCTION_ONLY"
    environment: str


class ValidatedOrderSpec(BaseModel, frozen=True):
    """
    Immutable explicit specification passed to mutation transports after side-aware quantization.
    """

    intent_id: str
    spec_hash: str
    quantized_qty: Decimal
    quantized_price: Decimal
    quantized_stop: Decimal
    quantized_tp: Decimal | None = None
    sl_trigger_by: str = "LastPrice"
    tpsl_mode: str = "Full"
    sl_order_type: str = "Market"


class NetworkPermit(BaseModel, frozen=True):
    """
    Immutable capability token granting mutation authority for a specific spec/environment/action.
    """

    permit_id: str
    submission_attempt_id: str
    logical_order_id: str
    action: PermitAction
    environment: str
    symbol: str
    validated_spec_hash: str
    authorization_event_id: str
    issued_at: float


class ExecutionFill(BaseModel, frozen=True):
    """
    A single execution/fill record from the exchange, uniquely identifiable for idempotent dedupe.
    """

    exec_id: str
    order_id: str
    order_link_id: str
    symbol: str
    side: SignalDirection
    exec_qty: Decimal
    exec_price: Decimal
    fee: Decimal
    timestamp: float
    environment: str


class QuarantineProjection(BaseModel, frozen=True):
    """
    Projection identifying an ambiguous execution and its conservative risk upper bound.
    """

    symbol: str
    logical_order_id: str
    submission_attempt_id: str
    quarantined_worst_case_risk: Decimal
    reason: str


class ExecutionStatus(StrEnum):
    """The outcome of an execution attempt (Phase 5)."""

    SUCCESS = "SUCCESS"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class ExecutionResult(BaseModel, frozen=True):
    """The immutable outcome of an execution attempt (Phase 5)."""

    decision_id: str = Field(
        ..., description="UUID connecting this execution to the original decision"
    )
    client_order_id: str = Field(..., description="Idempotency key sent to the exchange")
    exchange_order_id: str | None = Field(
        default=None, description="Order ID generated by the exchange"
    )

    status: ExecutionStatus = Field(..., description="Final or intermediate status")

    executed_qty: Decimal = Field(default=Decimal("0"))
    executed_price: Decimal = Field(default=Decimal("0"))

    submit_timestamp: float = Field(default=0.0)
    ack_timestamp: float = Field(default=0.0)
    complete_timestamp: float = Field(default=0.0)

    retry_count: int = Field(default=0)
    latency_ms: float = Field(default=0.0)

    error_code: str | None = Field(default=None)
    error_message: str | None = Field(default=None)


class ExecutionQuoteSnapshot(BaseModel, frozen=True):
    quote_id: str
    symbol: str
    bid: Decimal
    ask: Decimal
    source_market_timestamp: datetime
    received_at: datetime
    source: str


class PaperFillRole(StrEnum):
    ENTRY = "ENTRY"
    TP_EXIT = "TP_EXIT"
    SL_EXIT = "SL_EXIT"


class PaperPositionState(BaseModel, frozen=True):
    position_id: str
    symbol: str
    side: SignalDirection
    qty: Decimal
    entry_fill: Decimal
    entry_timestamp: float
    canonical_stop: Decimal
    canonical_tp: Decimal
    paper_policy_version: str


class PaperSimulationObservation(BaseModel, frozen=True):
    fill_id: str
    role: PaperFillRole
    qty: Decimal
    fill_price: Decimal
    fee: Decimal
    timestamp: float
    quote_id: str | None = None
    candle_timestamp: float | None = None
    net_pnl: Decimal | None = None
    realized_r: Decimal | None = None
