"""
MarketPilot Models - Execution domain models.
"""

from __future__ import annotations

from enum import Enum
from typing import Optional
from decimal import Decimal
from pydantic import BaseModel, Field

class ExecutionStatus(str, Enum):
    """The outcome of an execution attempt."""
    SUCCESS = "SUCCESS"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"
    MANUAL_REVIEW = "MANUAL_REVIEW"

class ExecutionResult(BaseModel, frozen=True):
    """The immutable outcome of an execution attempt, rich in metrics."""
    decision_id: str = Field(..., description="UUID connecting this execution to the original decision")
    client_order_id: str = Field(..., description="Idempotency key sent to the exchange")
    exchange_order_id: Optional[str] = Field(default=None, description="Order ID generated by the exchange")

    status: ExecutionStatus = Field(..., description="Final or intermediate status")

    executed_qty: Decimal = Field(default=Decimal("0"))
    executed_price: Decimal = Field(default=Decimal("0"))

    submit_timestamp: float = Field(default=0.0)
    ack_timestamp: float = Field(default=0.0)
    complete_timestamp: float = Field(default=0.0)

    retry_count: int = Field(default=0)
    latency_ms: float = Field(default=0.0)

    error_code: Optional[str] = Field(default=None)
    error_message: Optional[str] = Field(default=None)

class NetworkPermit(BaseModel, frozen=True):
    """
    Explicitly typed capability token granting Phase 6 the right to mutate the exchange.
    Generated ONLY by IdempotencyGate after intent is durably saved.
    """
    permit_id: str
    allocation_id: str
    symbol: str
    side: str
    quantity: str

    # Ensures the permit is traceable back to the IdempotencyGate sequence
    intent_journal_id: str
