"""
MarketPilot Models - Mission Control.

Models for the top-level orchestration, metrics, and event context.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime
from typing import Any, Optional
from pydantic import BaseModel, Field

class PipelineContext(BaseModel, frozen=True):
    """Immutable context passed through the entire event bus."""
    decision_id: str
    cycle_id: str
    config_hash: str
    market_time: datetime
    start_time: float
    daemon_instance_id: str = "unknown"
    engine_metadata: dict[str, Any] = Field(default_factory=dict)

class CycleSnapshot(BaseModel, frozen=True):
    """A snapshot of a single cycle execution."""
    cycle_id: str
    start_time: float
    end_time: float
    duration_ms: float
    symbols_scanned: int
    trades_generated: int
    trades_executed: int
    errors: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    snapshot_hash: str = Field(default="")
    
    def generate_hash(self) -> str:
        data = self.model_dump(exclude={"snapshot_hash"})
        return hashlib.sha256(json.dumps(data, sort_keys=True).encode()).hexdigest()

class MissionControlReport(BaseModel, frozen=True):
    """The final operational document generated by the Mission Control."""
    timestamp: float
    cycle_summary: CycleSnapshot
    health_snapshot: dict[str, Any]
    circuit_breaker_state: str
    performance_metrics: dict[str, Any]
    incident_list: list[str]
